### ISSUE TITLE
Build with node 12: update node-sass to 4.12+

### ISSUE THREAD

**Issue by julieni** [ovh-ux/manager#1343]
### Description

Cannot build with node 12, because of node-sass being < 4.12

### Steps to Reproduce

1. install node 12
2. yarn install

**Expected behavior:**

yarn should install and compile everything

**Actual behavior:**

compilation of node-sass fails, errors seems related to dependency package "nan"

**Reproduces how often:**

everytime

**Comment by antleblanc** [comment]
@julieni Since we have moved `ovh-ux/ovh-manager-telecom` repository into this monorepo we took the opportunity to bump `node-sass` to the latest version [4.12.0](https://github.com/sass/node-sass/releases/tag/v4.12.0).

Using `cat` command against our `yarn.lock` file now reports: 

```sh
antoine: ~/Code/github/ovh-ux/manager on master
$ cat yarn.lock  | grep -A 3 node-sass
node-sass@^4.10.0, node-sass@^4.11.0:
  version "4.12.0"
  resolved "https://registry.yarnpkg.com/node-sass/-/node-sass-4.12.0.tgz#0914f531932380114a30cc5fa4fa63233a25f017"
  integrity sha512-A1Iv4oN+Iel6EPv77/HddXErL2a+gZ4uBeZUy+a8O35CFYTXhgA8MgLCWBtwpGZdCvTvQ9d+bQxX/QC36GDPpQ==
  dependencies:
    async-foreach "^0.1.3"
```

I'm now able to both `build` and `start:dev` the `@ovh-ux/manager-telecom` application which is now located here:
- packages/manager/apps/telecom

Hope you find this useful.
